# Generated by Django 2.2.1 on 2019-05-21 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='stones',
            name='client',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
