# Generated by Django 2.2.1 on 2019-07-10 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=10)),
                ('x1', models.CharField(max_length=10)),
                ('y1', models.IntegerField()),
                ('x2', models.CharField(max_length=10)),
                ('y2', models.IntegerField()),
            ],
        ),
    ]
