# Generated by Django 2.2.1 on 2019-07-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omok', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientColor', models.CharField(max_length=10)),
            ],
        ),
    ]
