# Generated by Django 2.2.1 on 2019-07-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omok', '0002_clientcolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitStone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=10)),
                ('x', models.CharField(max_length=10)),
                ('y', models.IntegerField()),
            ],
        ),
    ]
