# Generated by Django 2.2.1 on 2019-07-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omok', '0003_initstone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InitStone',
            new_name='ResultOmok',
        ),
        migrations.AlterField(
            model_name='stone',
            name='x2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='stone',
            name='y2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
